# Generated by Django 4.1.2 on 2022-10-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='p_id',
            new_name='id',
        ),
    ]
